### ISSUE TITLE
jestPuppeteer.debug() broken if stdin is not a TTY

### ISSUE THREAD

**Issue by DavidJRobertson** [smooth-code/jest-puppeteer#120]
On my windows system w/ cygwin and conemu, jestPuppeteer.debug() results in this error:

```
TypeError: stdin.setRawMode is not a function
  at resolve (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:98:19)
  at Object.debug (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:84:16)
```

This appears to be related:
https://github.com/nodejs/node-v0.x-archive/issues/8204

**Comment by skipjack** [comment]
I'm seeing a similar issue, @DavidJRobertson did you ever find a workaround? I'm on macOS 10.14.3 running node 8.9.4.

**Comment by skipjack** [comment]
Due to the fact that this fails, I've been using other methods to debug like setting `headless: false` and calling `jest.setTimeout` which work ok for debugging but cause tests to fail that normally pass when it is running headless. I'm assume changing the `headless` option shouldn't cause the non-deterministic results but maybe I'm wrong.

@neoziro before I file separate issues, are those things to be expected? Does `jestPuppeteer.debug()` account for a lot of edge cases? If that's the case, I'll probably wait for this to be resolved before filing anything else.

Thanks for this package btw, aside from some minor debugging hiccups `jest` and `jest-puppeteer` have been pretty easy (and enjoyable) to figure out and start using.

**Comment by skipjack** [comment]
Ok here's some updates...

I don't get the error in the OP if `headless` or `devtools` (or both) are set:

__jest-puppeteer.config.js__

``` js
module.exports = {
    launch: {
        headless: false,
        devtools: true
    }
}
```

Using the approach from [this comment](https://github.com/smooth-code/jest-puppeteer/issues/106#issuecomment-413344050) was also the only thing that made `jestPuppeteer.debug()` work for me. Obviously #106 is somewhat related to this one.

Still seeing some other weirdness but maybe this issue can be closed by documenting the need for `headless: false` or `devtools: true`.

**Comment by skipjack** [comment]
Edited the above comment, it seems both or at least `devtools`, is required.

**Comment by michaelmang** [comment]
The [documentation](https://github.com/smooth-code/jest-puppeteer#extend-puppeteerenvironment) mentions how to extend `PuppeteerEnvironment`.

Adding `tty` to the environment resolved this issue for me:

```javascript
const PuppeteerEnvironment = require('jest-environment-puppeteer')
const tty = require('tty'); // added this

class CustomEnvironment extends PuppeteerEnvironment {
  async setup() {
    await super.setup()
  }

  async teardown() {
    await super.teardown();
  }
}

module.exports = CustomEnvironment
```

**Comment by gregberge** [comment]
Stale, feel free to open a new issue if you have this problem.
