### ISSUE TITLE
Load jest-puppeteer.config.js from <rootDir>

### ISSUE THREAD

**Issue by donaldpipowitch** [smooth-code/jest-puppeteer#160]
## 🚀 Feature Proposal

When I place my Jest config in a sub-directory my tests actually have a new `<rootDir>`, but the `jest-puppeteer.config.js` is still loaded from the root of my project.

```
- jest-puppeteer.config.js
- tests/jest.config.js

$ jest --config tests/jest.config.js
```

It would be nice however, if I could do this _by default_.

```
- tests/jest-puppeteer.config.js
- tests/jest.config.js

$ jest --config tests/jest.config.js
```

## Motivation

IMHO it is more natural to respect the `<rootDir>` of Jest and easier to learn/to "do right". Currently I can set `JEST_PUPPETEER_CONFIG`, but this is something I need to look up and it is also less "shareable".

An alternative to get rid of `JEST_PUPPETEER_CONFIG` in the case you don't wan't to respect `<rootDir>` by default would be to make it configurable similar to [how `ts-jest` handles the `tsconfig.json`](https://kulshekhar.github.io/ts-jest/user/config/tsConfig):

```
module.exports = {
  globals: {
    'jest-puppeteer': {
      config: '<rootDir>/jest-puppeteer.config.js'
    }
  }
};
```

That is still something I need to look up, but at least it is easier to share and I can use `<rootDir>`.

## Example

If you don't place your Jest configs in sub-directories everything still works like usual:

```
- jest-puppeteer.config.js
- jest.config.js

$ jest
```

If you _do_ place your Jest configs in sub-directories, you can place the corresponding `jest-puppeteer.config.js` in the same directory without the need to add custom environment variables.

```
- tests/jest-puppeteer.config.js
- tests/jest.config.js

$ jest --config tests/jest.config.js
```

## Pitch

> Why does this feature belong in the SVGR ecosystem?

What is the SVGR ecosystem?

**Comment by neoziro** [comment]
Hello @donaldpipowitch, originally I would like to get rid of `jest-puppeteer.config.js` (see #111).

It is actually blocked because a part of config is not avalaible in global hooks.

Maybe using `globals` entry could solve the problem, could you give a deeper look? If we could remove this file it would be great.

If we can’t I don’t want to invest more effort on it, I prefer to submit some changes in Jest to be able to get rid of it.

**Comment by neoziro** [comment]
I just gave a look, `globals` are not exposed in `globalConfig`, the only config available in `globalSetup` and `globalTeardown`. So actually it is not possible to use it (https://github.com/facebook/jest/blob/master/packages/jest-config/src/index.js#L102).

We are stuck :(

**Comment by donaldpipowitch** [comment]
I see :(

**Comment by DavidBabel** [comment]
Any information of this proposal ? 

I face the same problem

**Comment by Macil** [comment]
Right now, you can make jest-puppeteer load jest-puppeteer.config.js from the same directory as jest.config.js by putting this in your jest.config.js:

```js
process.env.JEST_PUPPETEER_CONFIG = require.resolve('./jest-puppeteer.config.js');
```

(I'd love it if this wasn't necessary and was the default behavior.)

**Comment by DavidBabel** [comment]
Thanks @Macil , it's still a good workaround

**Comment by thernstig** [comment]
https://github.com/smooth-code/jest-puppeteer#jest-puppeteerconfigjs specifically says:

> You can specify a jest-puppeteer.config.js at the root of the project

Considering "root" is often used as "rootDir" [in Jest config](https://jestjs.io/docs/en/configuration#rootdir-string) and also if you use the 'projects' property, it would be nice to at least use <rootDir> in the code where it is called.

I understand you might want to get rid of jest-puppeteer.config.js but as the issue was submitted a year ago, maybe this could be considered anyway as it makes it more natural than using the env var?

**Comment by gregberge** [comment]
Stale, feel free to open a new issue if you have this problem.
