### ISSUE TITLE
PuppeteerEnvironment: use of jest-environment-node over jest-environment-jsdom

### ISSUE THREAD

**Issue by dmnsgn** [smooth-code/jest-puppeteer#179]
Hi,

I am simply wondering why the jest PuppeteerEnvironment is extending a node environment instead of the default jsdom?

Here: https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js#L2

I am coming across this while I was trying to write a test with `.toBeInstanceOf(CanvasRenderingContext2D);` (assuming jsdom supports CanvasRenderingContext2D but that's not the point here).

**Comment by neoziro** [comment]
Hello @dmnsgn, the answer is simple: you don't need JSDOM to run Puppeteer. Also what you were trying to achieve (`.toBeInstanceOf(CanvasRenderingContext2D)`) could not work because the instance of `CanvasRenderingContext2D` in JSDOM is not the same as the instance in Puppeteer. In Puppeteer you run in the browser, in fact you just "send code" threw an API to the browser.

I don't know if I am very clear in my explanations, am I?

**Comment by dmnsgn** [comment]
Hi @neoziro,

Thanks for the explanation, it does make sense. To sum up, having test with jsdom and jest-puppeteer is antithetical as the latter runs on node directly.
`expect-puppeteer` isn't designed to do instance check/object related tests, but that may be the case at some point?
Closing this, as my approach isn't probably doable like this.
