### ISSUE TITLE
How to ensure running jest test after a server is started

### ISSUE THREAD

**Issue by theniceangel** [smooth-code/jest-puppeteer#189]
```js
module.exports = {
  server: {
    command: `npm start`
  }
}
```
Usually, executing server.command offen need a long time to start a server, but running jest tests is going on, so I want to do tests after a server is started.

**Comment by xiaoyuhen** [comment]
hi, @theniceangel 
There is a lot of discussion about this issue here. see https://github.com/smooth-code/jest-puppeteer/issues/113

For now, You can use these methods to solve this issue

### Listening service output

You can use the ```getServers``` method to listen for process output information, then parsing stdout or waiting on an IPC message

### Start the service with content that has already been built

In most cases, this problem occurs because the service is already started when the build is not successful.

So, you can build before starting the service and then start the service with the existing build content.

**Comment by theniceangel** [comment]
Thank you, I will do a try
