### ISSUE TITLE
Where to specify puppeteer.use()?

### ISSUE THREAD

**Issue by undrafted** [smooth-code/jest-puppeteer#260]
Could be a newbie question, or i've overlooked the readme - but I'm trying to add a puppeteer-extra plugin, i would like to know how to set up puppeteer since we are using ```jest-puppeteer.config.js```?

Example:
```js
// Add stealth plugin and use defaults (all tricks to hide puppeteer usage)
const StealthPlugin = require("puppeteer-extra-plugin-stealth")
puppeteer.use(StealthPlugin()) 
```

**Comment by neoziro** [comment]
It is not yet supported, sorry.

**Comment by quetzalsly** [comment]
When will this be supported? it's been a long time now.

**Comment by timothywangdev** [comment]
it's gonna be quite helpful

**Comment by Macil** [comment]
You can use puppeteer-extra with jest-puppeteer by putting this in jest-puppeteer.config.js:

```js
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
puppeteer.use(StealthPlugin());

require.cache[require.resolve('puppeteer')] =
  require.cache[require.resolve('puppeteer-extra')];
```

**Comment by bvanhou** [comment]
@Macil Would you be able to give an example of the full file `jest-puppeteer.config.js`

**Comment by Macil** [comment]
The rest of the file can be normal. I guess if you didn't have a jest-puppeteer.config.js file before and have nothing else to put into it, then you should make it at least export an empty config object:

```js
module.exports = {};
```

**Comment by enuchi** [comment]
Thanks @Macil. This seemed to get `puppeteer-extra-plugin-stealth` working partially for me, but caused other issues with my tests (tests would pass but suite would fail). Perhaps because of sharing cache? Not sure why.

If it helps anyone, the only way I could get `puppeteer-extra-plugin-stealth` working was to not use `jest-puppeteer` and instead do a custom jest/puppeteer setup as described in the jest docs here: https://jestjs.io/docs/puppeteer#custom-example-without-jest-puppeteer-preset.
