### ISSUE TITLE
Puppeteer v2.1.0 supports Firefox out of the box

### ISSUE THREAD

**Issue by Angelmmiguel** [smooth-code/jest-puppeteer#312]
## 🚀 Feature Proposal

The new version of Puppeteer ([v2.1.0](https://github.com/puppeteer/puppeteer/releases/tag/v2.1.0)) supports Firefox without requiring to install the `puppeteer-firefox` package.

You can configure Firefox directly on the `puppeteer.lunch` call:

```
puppeteer.launch({product: 'firefox'})
```

## Motivation

Currently, this package uses the experimental package to provide Firefox support. However, this method is deprecated.

## Example

We should be able to configure it using the regular configuration parameter:

```
// jest-puppeteer.config.js
module.exports = {
  launch: {
    product: "firefox"
  }
};
```

## Pitch

Because this is a new feature provided by the puppeteer team.

**Comment by fregante** [comment]
It appears that this issue has been fixed by https://github.com/smooth-code/jest-puppeteer/pull/356, however jest still throws this error:

```
Error: Jest: Got error running globalSetup - ./node_modules/jest-environment-puppeteer/setup.js, reason: Could not find expected browser (firefox) locally. Run `PUPPETEER_PRODUCT=firefox npm install` to download a supported Firefox browser binary.
    at FirefoxLauncher.launch (./node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:194:23)
```

I tried deleting `node_modules` and running `PUPPETEER_PRODUCT=firefox npm install puppeteer` as [puppeteer’s docs](https://github.com/puppeteer/puppeteer/blob/v10.0.0/docs/api.md#puppeteerproduct) suggest, but no luck.

Running on macOS 11.4, Node 15, latest Chrome and Firefox installed locally.
