### ISSUE TITLE
How to use with create-react-app

### ISSUE THREAD

**Issue by chris-fa** [smooth-code/jest-puppeteer#61]
I want to leave the default config CRA comes with for unit tests, and then add puppeteer and have e2e tests in a different directory.

So far I've tried the following:

1. create `jest-e2e.config.js` and add `"test:e2e": "jest -c jest-e2e.config.js",` to `package.json`

```
module.exports = {
  preset: 'jest-puppeteer',
  testRegex: "e2e/tests/.*\\.test\\.js$"
};
```

2. Add tests inside `e2e/tests/` directory

It doesn't work, it says page is not defined.

How can I accomplish this?

**Comment by neoziro** [comment]
I think you got `page is undefined` when you run `npm test` because it will also run the tests in E2E without the `jest-puppeteer` preset. You have to ignore these tests in the `npm test` command. 

The simplest thing to do seems to name your E2E tests with only `.js` and to change your "testRegex". Then you can escape [the default "testRegex" specified in create-react-app](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#filename-conventions).

**Comment by Grsmto** [comment]
I was actually about to ask the same question and I named my tests `filename.test.e2e.js` and it works perfectly! I didn't test in a CRA context but that should work the same way as the default jest pattern seems to be the same as CRA one (https://facebook.github.io/jest/docs/en/configuration.html#testmatch-array-string)

**Comment by chris-fa** [comment]
I got it working by having a different `jest-e2e.config.js` and running it explicitly: `yarn jest -c jest-e2e.config.js`; and by upgrading to `react-scripts@next` to have Jest 22.  I'm not sure if there's a way to use it with the CRA default Jest configuration
